# Site settings
title: 國立臺北科技大學資訊工程系學會 NTUT CSIE Student Association
title_short: NTUT CSIE SA
header-img: img/home-bg.jpg
copyright_name: 國立臺北科技大學資訊工程系學會 NTUT CSIE Student Association
description: "Student Association, Department of Computer Science and Information Engineering, National Taipei University of Technology."
baseurl: ""
url: "http://csie.ntut.cc"
github_username:  ntutcsie
facebook_username:  ntutcsieFB
email_username:  csie.sa@ntut.edu.tw
facebook_plugin:
    appId: 255130074525581
    language: "zh_TW"
    name: "國立臺北科技大學資訊工程系-系學會專頁"
    username: ntutcsieFB
    height: 250
    width: 450
    tabs: "messages, timeline"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
